#%RAML 1.0 NamedExample


  {
                          "1": "Dua Lipa",
                          "2": "Ed Sheeran",
                          "3": "Coldplay",
                          "4": "One Direction"
                        }