#%RAML 1.0 NamedExample

{
                          "1": "Travelling",
                          "2": "Monsoon",
                          "3": "Workout",
                          "4": "Motivational"
                        }