#%RAML 1.0 NamedExample


  {
                        "1": "Hey Brother. Avicii",
                        "2": "See You Again (feat. Charlie Puth) Wiz Khalifa",
                        "3": "Wake Me Up. Avicii",
                        "4": "Shivers. Ed Sheeran."
                        }
