#%RAML 1.0 NamedExample


  {
                          "1": "Heavyweight",
                          "2": "Reply All",
                          "3": "60 Songs That Explain the 90s",
                          "4": "Armchair Expert"
                          }